### PR TITLE
add localized abbreviations for m/km

### PR DESCRIPTION
**Pull request by westnordost**
Researched by looking at all articles in all languages linked from https://en.wikipedia.org/wiki/Metre 😅

Only added strings.xml for languages that have an ISO 639-1 or ISO 639-2 code. (I.e. not ISO 639-3 because[ that isn't supported anyway](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-resources-setup.html#language-and-regional-qualifiers))

"m" should actually be quite understood anywhere, but some languages have an abbreviation in their own script that is preferred over the international symbol ("m").

There are no translations for feet, because feet is only really used in the US, i.e. in an English-speaking country. Hence, in other languages, an abbreviation doesn't really exist.

### CODE REVIEW

**Comment by sargunv** [comment]
thanks for this!

I went ahead and removed japanese (as it's the same m and km as english) and added pies for spanish

**Comment by westnordost** [comment]
Well, I added Japanese for the comment. To denote "yes, it has been checked, but it is really m/km"

**Comment by sargunv** [comment]
In that case I’d do the same for Korean, Hindi, Telegu, just about everything with a non Latin script that uses Latin style symbols for SI units. Is there a particular reason to comment for Japanese specifically?

**Comment by westnordost** [comment]
It was specifically mentioned in the wiki article (that till X, some character was used bit it isn't anymore)

**Pull request merged**
